CREATE TABLE Palpiteiros (
    TelegramID int,
    Nome char(255),
    Pontos INT DEFAULT '0', 
	catFilme char(3) DEFAULT '0',         
    catDirecao char(3) DEFAULT '0',
    catFotografia char(3) DEFAULT '0',    
    catArte char(3) DEFAULT '0',
    catrotAdapt char(3) DEFAULT '0',      
    catrotOrig char(3) DEFAULT '0',
    catAtriz char(3) DEFAULT '0',         
    catAtor char(3) DEFAULT '0',
    catAtrizCoad char(3) DEFAULT '0',     
    catAtorCoad char(3) DEFAULT '0',
    catEfeitos char(3) DEFAULT '0',       
    catEdicao char(3) DEFAULT '0',
    catAnimacao char(3) DEFAULT '0',      
    catEstrangeiro char(3) DEFAULT '0',
    catMixSom char(3) DEFAULT '0',        
    catEdiSom char(3) DEFAULT '0',
    catFigurino char(3) DEFAULT '0',      
    catMaquiagem char(3) DEFAULT '0',
    catDocumentario char(3) DEFAULT '0',  
    catTrilha char(3) DEFAULT '0',
    catCurta char(3) DEFAULT '0',         
    catMusica char(3) DEFAULT '0',
    catAnimacaoCurta char(3) DEFAULT '0', 
    catDocCurta char(3) DEFAULT '0'
);